<a href="https://colab.research.google.com/github/z-arabi/Machine-Learning/blob/main/logistic_regression_2_Multiclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/z-arabi/Machine-Learning.git
%cd Machine-Learning

Cloning into 'Machine-Learning'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 40 (delta 10), reused 10 (delta 1), pack-reused 0
Unpacking objects: 100% (40/40), done.
/content/Machine-Learning


In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
%matplotlib inline

In [32]:
df = pd.read_csv('./Datasets/datasets_738_1370_glass.csv')
df.head(5)

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [33]:
df.Type.unique()

array([1, 2, 3, 5, 6, 7])

In [34]:
df.Type.value_counts()

2    76
1    70
7    29
3    17
5    13
6     9
Name: Type, dtype: int64

In [35]:
X = df.to_numpy()

In [36]:
y = X[:, -1]
X = X[:, :-1]

In [37]:
X = (X - X.mean(axis=0)) / X.std(axis=0)

In [43]:
# ovr = ova // multinomial = ovo
# class_weight > give different weights to classes to make the imbalanced classes to have same impact
# w{yi} * (hi - yi) * xi
clf = LogisticRegression(multi_class='ovr', class_weight='balance', max_iter=1000)

In [39]:
clf.fit(X, y)

LogisticRegression(class_weight='balance', max_iter=1000, multi_class='ovr')

In [40]:
clf.score(X, y)

0.6869158878504673

In [41]:
clf.predict(X)

array([1., 1., 2., 1., 1., 2., 1., 1., 1., 1., 2., 1., 2., 1., 1., 1., 1.,
       1., 1., 2., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1., 1.,
       2., 1., 2., 2., 2., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2., 2., 1., 1., 2., 2.,
       2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 1., 2., 2., 2., 2.,
       1., 1., 2., 5., 2., 2., 6., 6., 2., 2., 2., 1., 1., 1., 2., 2., 2.,
       2., 1., 2., 2., 2., 1., 2., 1., 2., 2., 2., 2., 2., 1., 2., 1., 2.,
       1., 2., 1., 2., 2., 1., 2., 2., 2., 2., 1., 1., 2., 2., 2., 1., 1.,
       1., 2., 1., 1., 1., 2., 2., 2., 1., 2., 7., 2., 2., 2., 5., 5., 5.,
       2., 5., 5., 5., 2., 2., 2., 2., 6., 2., 6., 6., 6., 6., 6., 7., 7.,
       1., 2., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 5., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [42]:
clf.predict_proba(X)

array([[5.36391416e-01, 3.00033538e-01, 1.36791110e-01, 9.73752415e-04,
        2.09301423e-02, 4.88004177e-03],
       [4.95711964e-01, 3.20028903e-01, 9.04211507e-02, 4.81473420e-03,
        4.14581344e-02, 4.75651141e-02],
       [3.75866569e-01, 4.25354994e-01, 1.07220441e-01, 1.04385844e-02,
        3.91400327e-02, 4.19793790e-02],
       ...,
       [3.59520787e-03, 2.23487311e-02, 2.06963349e-04, 3.25714735e-03,
        1.03122906e-03, 9.69560721e-01],
       [2.65489324e-03, 2.15291856e-02, 1.65889685e-03, 5.16132553e-03,
        2.36777950e-03, 9.66627919e-01],
       [1.82609740e-03, 2.74714644e-02, 1.41547178e-03, 8.02146856e-03,
        1.16397668e-03, 9.60101521e-01]])